{% set name = "aspy.yaml" %}
{% set version = "1.3.0" %}
{% set hash = "3413c6a1213684ccebed70bc7ec11c5f19eff38dde07e8998e729df8b7668693" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/asottile/aspy.yaml/archive/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 1
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - pyyaml

test:
  imports:
    - aspy
    - aspy.yaml
  requires:
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: http://github.com/asottile/aspy.yaml
  license: MIT
  summary: 'A few extensions to pyyaml.'
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicoddemus
